name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/metrics.yml"
  workflow_dispatch:

concurrency:
  group: metrics
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Base
          base: header, activity, community, repositories
          base_hireable: true
          repositories_affiliations: owner, collaborator

          # Core
          config_timezone: America/Los_Angeles

          # Isometric calendar
          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year

          # Languages
          plugin_languages: true
          plugin_languages_details: percentage
          plugin_languages_other: true
          plugin_languages_ignored: html, css, javascript

          # Lines
          plugin_lines: true

          # Traffic
          plugin_traffic: true
