name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Base
          base: header, activity, community, repositories
          base_hireable: yes
          repositories_affiliations: owner, collaborator

          # Core
          config_display: columns

          # Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages
          plugin_languages: yes
          plugin_languages_other: yes

          # Lines
          plugin_lines: yes

          # Traffic
          plugin_traffic: yes
